name: 'changelog-template-action'
description: 'Generate changelogs from templates with reference to git history, tags and merged pull requests'
author: 'srz_zumix'
inputs:
  owner:
    description: 'git repository owner'
    default: "${{ github.repository_owner }}"
    required: false
  repo:
    description: 'git repository name'
    default: "${{ github.event.repository.name }}"
    required: false
  git_url:
    description: 'git repository url (owner/repo inputs are ignored)'
    required: false
  template:
    description: 'Template text'
    required: false
  template_file:
    description: 'Template file path'
    required: false
  output_file:
    description: 'Output file path'
    required: false
  from:
    description: 'git commit revision range start from'
    required: false
  to:
    description: 'git commit revision range end to'
    required: false
  kamidana_additionals:
    description: 'kamidana additionals modules'
    required: false
  comment_to_issue:
    description: 'issue or pull request number to post comment (if not set, no comment)'
    required: false
  comment_mode:
    description: 'update or hide previous comment [update|hide]'
    default: 'hide'
    required: false
  tee:
    description: 'tee gh / kamidana output'
    default: false
    required: false
  debug:
    description: 'enable debug'
    default: false
    required: false

outputs:
  text:
    description: "jinja2 output text"
    value: ${{ steps.kamidana.outputs.text }}
  owner:
    description: "resolved owner"
    value: ${{ steps.resolve-owner-repo.outputs.owner }}
  repo:
    description: "resolved repo"
    value: ${{ steps.resolve-owner-repo.outputs.repo }}
  from:
    description: "resolved from"
    value: ${{ steps.resolve-from-to.outputs.from }}
  to:
    description: "resolved to"
    value: ${{ steps.resolve-from-to.outputs.to }}
  commit_count:
    description: "resolved from...to commit count"
    value: ${{ steps.resolve-from-to.outputs.commit_count }}

runs:
  using: "composite"
  steps:
    - name: resolve owner/repo
      id: resolve-owner-repo
      shell: bash
      env:
        INPUTS_OWNER: "${{ inputs.owner }}"
        INPUTS_REPO: "${{ inputs.repo }}"
        INPUTS_GIT_URL: "${{ inputs.git_url }}"
        INPUTS_DEBUG: "${{ inputs.debug }}"
      run: "${GITHUB_ACTION_PATH}/resolve-owner-repo.sh"
    - name: resolve from-to
      id: resolve-from-to
      shell: bash
      env:
        INPUTS_OWNER: "${{ steps.resolve-owner-repo.outputs.owner }}"
        INPUTS_REPO: "${{ steps.resolve-owner-repo.outputs.repo }}"
        INPUTS_FROM: "${{ inputs.from }}"
        INPUTS_TO: "${{ inputs.to }}"
        INPUTS_DEBUG: "${{ inputs.debug }}"
      run: "${GITHUB_ACTION_PATH}/resolve-from-to.sh"
    - name: create associatedPullRequests.json
      shell: bash
      env:
        INPUTS_OWNER: "${{ steps.resolve-owner-repo.outputs.owner }}"
        INPUTS_REPO: "${{ steps.resolve-owner-repo.outputs.repo }}"
        INPUTS_FROM: "${{ steps.resolve-from-to.outputs.from }}"
        INPUTS_TO: "${{ steps.resolve-from-to.outputs.to }}"
        COMMIT_COUNT: "${{ steps.resolve-from-to.outputs.commit_count }}"
        INPUTS_TEE: "${{ inputs.tee }}"
        INPUTS_DEBUG: "${{ inputs.debug }}"
      run: |
        if [ "${INPUTS_TEE}" == 'true' ]; then
          "${GITHUB_ACTION_PATH}/associatedPullRequests.sh" | tee "${{ runner.temp }}/associatedPullRequests.json"
        else
          "${GITHUB_ACTION_PATH}/associatedPullRequests.sh" > "${{ runner.temp }}/associatedPullRequests.json"
        fi
    - name: create inputs.json
      shell: bash
      env:
        INPUTS_OWNER: "${{ steps.resolve-owner-repo.outputs.owner }}"
        INPUTS_REPO: "${{ steps.resolve-owner-repo.outputs.repo }}"
        INPUTS_FROM: "${{ steps.resolve-from-to.outputs.from }}"
        INPUTS_TO: "${{ steps.resolve-from-to.outputs.to }}"
        INPUTS_CONTEXT: "${{ toJson(inputs) }}"
      run: |
        {
          echo "{"
          echo "  \"owner\": \"${INPUTS_OWNER}\","
          echo "  \"repo\": \"${INPUTS_REPO}\","
          echo "  \"from_revision\": \"${INPUTS_FROM}\","
          echo "  \"to_revision\": \"${INPUTS_TO}\""
          echo "}"
        } > "${{ runner.temp }}/revision.json"
        echo "${INPUTS_CONTEXT}" | jq "del(.github_token,.debug) | { inputs: . }" > "${{ runner.temp }}/inputs.json"
    - name: create template file
      id: create-template-file
      shell: bash
      run: |
        cat << 'EOS' > "${{ runner.temp }}/template.j2"
        ${{ inputs.template }}
        EOS
        echo "path=${{ runner.temp }}/template.j2" >> "${GITHUB_OUTPUT}"
      if: inputs.template_file == ''
    - name: kamidana
      id: kamidana
      uses: srz-zumix/kamidana-action@f83fd111b652b0833f00f32a41b45945fb343778 # v2.7.0
      with:
        template: "${{ inputs.template_file || steps.create-template-file.outputs.path }}"
        output_file: "${{ runner.temp }}/changelog.md"
        data_files: |
          ${{ runner.temp }}/associatedPullRequests.json
          ${{ runner.temp }}/revision.json
          ${{ runner.temp }}/inputs.json
        input_format: "json"
        tee: "${{ inputs.tee }}"
        additonals: "${{ inputs.kamidana_additionals }}"
        extensions: |
          i18n
          do
          loopcontrols
          debug
    - name: Copy to output file
      shell: bash
      env:
        INPUTS_OUTPUT_FILE: "${{ inputs.output_file }}"
      run: |
        if [ "${INPUTS_OUTPUT_FILE}" != "${{ runner.temp }}/changelog.md" ]; then
          cp "${{ runner.temp }}/changelog.md" "${INPUTS_OUTPUT_FILE}"
        fi
      if: inputs.output_file != ''
    - name: Aqua install
      uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
      with:
        aqua_version: v2.53.9
        aqua_opts: "-t action"
        working_directory: ${{ github.action_path }}
      if: inputs.comment_to_issue != ''
    - name: Hide old comment
      shell: bash
      env:
        INPUTS_OWNER: "${{ steps.resolve-owner-repo.outputs.owner }}"
        INPUTS_REPO: "${{ steps.resolve-owner-repo.outputs.repo }}"
        GITHUB_TOKEN: ${{ github.token }}
      run: github-comment hide -k changelog -v "repository:${INPUTS_OWNER}/${INPUTS_REPO}"
      working-directory: ${{ github.action_path }}
      if: inputs.comment_to_issue != '' && inputs.comment_mode == 'hide'
    - name: Comment to
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUTS_OWNER: "${{ steps.resolve-owner-repo.outputs.owner }}"
        INPUTS_REPO: "${{ steps.resolve-owner-repo.outputs.repo }}"
        INPUTS_COMMENT_TO_ISSUE: "${{ inputs.comment_to_issue }}"
        INPUTS_COMMENT_MODE: ${{ inputs.comment_mode }}
      run: |
        GITHUB_COMMENT_OPTIONS=()
        if [ "${INPUTS_COMMENT_MODE}" != 'hide' ]; then
          GITHUB_COMMENT_OPTIONS+=('-u' 'Comment.Meta.Vars.target == "changelog" && Comment.Meta.Vars.repository == Vars.repository')
        fi
        set -x
        github-comment post \
          --org "${INPUTS_OWNER}" \
          --repo "${INPUTS_REPO}" \
          --pr "${INPUTS_COMMENT_TO_ISSUE}" \
          "${GITHUB_COMMENT_OPTIONS[@]}" \
          -k changelog \
          -v "repository:${INPUTS_OWNER}/${INPUTS_REPO}" \
          --stdin-template < "${{ runner.temp }}/changelog.md"
      working-directory: ${{ github.action_path }}
      if: inputs.comment_to_issue != ''

branding:
  icon: 'sliders'
  color: 'yellow'
