name: 'changelog-template-action'
description: 'Generate changelogs from templates with reference to git history, tags and merged pull requests'
author: 'srz_zumix'
inputs:
  owner:
    description: 'git repository owner'
    default: "${{ github.repository_owner }}"
    required: false
  repo:
    description: 'git repository name'
    default: "${{ github.event.repository.name }}"
    required: false
  git_url:
    description: 'git repository url (owner/repo inputs are ignored)'
    required: false
  template_file:
    description: 'Template file path'
    required: true
  output_file:
    description: 'Output file path'
    required: false
  from:
    description: 'git commit revision range start from'
    required: false
  to:
    description: 'git commit revision range end to'
    required: false
  kamidana_additionals:
    description: 'kamidana additionals modules'
    required: false
  tee:
    description: 'tee gh / kamidana output'
    default: false
    required: false
  debug:
    description: 'enable debug'
    default: false
    required: false

outputs:
  text:
    description: "jinja2 output text"
    value: ${{ steps.kamidana.outputs.text }}
  owner:
    description: "resolved owner"
    value: ${{ steps.resolve-owner-repo.outputs.owner }}
  repo:
    description: "resolved repo"
    value: ${{ steps.resolve-owner-repo.outputs.repo }}
  from:
    description: "resolved from"
    value: ${{ steps.resolve-from-to.outputs.from }}
  to:
    description: "resolved to"
    value: ${{ steps.resolve-from-to.outputs.to }}

runs:
  using: "composite"
  steps:
    - name: resolve owner/repo
      id: resolve-owner-repo
      shell: bash
      env:
        INPUTS_OWNER: "${{ inputs.owner }}"
        INPUTS_REPO: "${{ inputs.repo }}"
        INPUTS_GIT_URL: "${{ inputs.git_url }}"
        INPUTS_DEBUG: "${{ inputs.debug }}"
      run: "${GITHUB_ACTION_PATH}/resolve-owner-repo.sh"
    - name: resolve from-to
      id: resolve-from-to
      shell: bash
      env:
        INPUTS_OWNER: "${{ steps.resolve-owner-repo.outputs.owner }}"
        INPUTS_REPO: "${{ steps.resolve-owner-repo.outputs.repo }}"
        INPUTS_FROM: "${{ inputs.from }}"
        INPUTS_TO: "${{ inputs.to }}"
        INPUTS_DEBUG: "${{ inputs.debug }}"
      run: "${GITHUB_ACTION_PATH}/resolve-from-to.sh"
    - name: create associatedPullRequests.json
      shell: bash
      env:
        INPUTS_OWNER: "${{ steps.resolve-owner-repo.outputs.owner }}"
        INPUTS_REPO: "${{ steps.resolve-owner-repo.outputs.repo }}"
        INPUTS_FROM: "${{ steps.resolve-from-to.outputs.from }}"
        INPUTS_TO: "${{ steps.resolve-from-to.outputs.to }}"
        INPUTS_TEE: "${{ inputs.tee }}"
        INPUTS_DEBUG: "${{ inputs.debug }}"
      run: |
        if [ "${INPUTS_TEE}" == 'true' ]; then
          "${GITHUB_ACTION_PATH}/associatedPullRequests.sh" | tee "${{ runner.temp }}/associatedPullRequests.json"
        else
          "${GITHUB_ACTION_PATH}/associatedPullRequests.sh" > "${{ runner.temp }}/associatedPullRequests.json"
        fi
    - name: create inputs.json
      shell: bash
      env:
        INPUTS_OWNER: "${{ steps.resolve-owner-repo.outputs.owner }}"
        INPUTS_REPO: "${{ steps.resolve-owner-repo.outputs.repo }}"
        INPUTS_FROM: "${{ steps.resolve-from-to.outputs.from }}"
        INPUTS_TO: "${{ steps.resolve-from-to.outputs.to }}"
        INPUTS_CONTEXT: "${{ toJson(inputs) }}"
      run: |
        {
          echo "{"
          echo "  \"owner\": \"${INPUTS_OWNER}\","
          echo "  \"repo\": \"${INPUTS_REPO}\","
          echo "  \"from_revision\": \"${INPUTS_FROM}\","
          echo "  \"to_revision\": \"${INPUTS_TO}\""
          echo "}"
        } > "${{ runner.temp }}/revision.json"
        echo "${INPUTS_CONTEXT}" | jq "del(.github_token,.debug) | { inputs: . }" > "${{ runner.temp }}/inputs.json"
    - name: kamidana
      id: kamidana
      uses: srz-zumix/kamidana-action@main
      with:
        template: "${{ inputs.template_file }}"
        output_file: "${{ inputs.output_file }}"
        data_files: |
          ${{ runner.temp }}/associatedPullRequests.json
          ${{ runner.temp }}/revision.json
          ${{ runner.temp }}/inputs.json
        input_format: "json"
        tee: "${{ inputs.tee }}"
        additonals: "${{ inputs.kamidana_additionals }}"
        extensions: |
          i18n
          do
          loopcontrols
          with_
          autoescape
          debug


branding:
  icon: 'sliders'
  color: 'yellow'
