name: 'changelog-template-action'
description: 'Generate changelogs from templates with reference to git history, tags and merged pull requests'
author: 'srz_zumix'
inputs:
  template_file:
    description: 'Template file path'
    required: true
  output_file:
    description: 'Output file path'
    required: false
  from:
    description: 'git commit revision range start from'
    required: false
  to:
    description: 'git commit revision range end to'
    required: false
  path:
    description: 'git repository path'
    default: '.'
    required: false
  github_token:
    description: 'git repository access token'
    default: "${{ github.token }}"

outputs:
  text:
    description: "jinja2 output text"
    value: ${{ steps.kamidana.outputs.text }}

runs:
  using: "composite"
  steps:
    - name: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION || '3.10' }}
        # cache: 'pip'
        # cache-dependency-path: ${{ github.action_path  }}/requirements.txt
    - name: pip install
      shell: bash
      run: |
        pip install jinja2-cli
    - name: setup-go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.8.5'
    - name: install ghch
      shell: bash
      run: |
        go install github.com/Songmu/ghch/cmd/ghch@latest
    - name: resolve from-to
      id: resolve-from-to
      shell: bash
      env:
        INPUTS_FROM: "${{ inputs.from }}"
        INPUTS_TO: "${{ inputs.to }}"
        INPUTS_PATH: "${{ inputs.path }}"
        GITHUB_TOKEN: "${{ inputs.github_token }}"
      run: "${GITHUB_ACTION_PATH}/resolve-from-to.sh"
    - name: create changelog json
      env:
        GITHUB_TOKEN: "${{ inputs.github_token }}"
      shell: bash
      run: |
        ghch --format=json \
          --from="${{ steps.resolve-from-to.outputs.from }}" \
          --to="${{ steps.resolve-from-to.outputs.to }}" \
          --token="${GITHUB_TOKEN}" \
          --repo="${{ inputs.path }}" \
          > "${{ runner.temp }}/ghch-changelog.json"
          cat "${{ runner.temp }}/ghch-changelog.json"
    - name: kamidana
      id: kamidana
      uses: srz-zumix/kamidana-action@main
      with:
        template: "${{ inputs.template_file }}"
        output_file: "${{ inputs.output_file }}"
        data_file: "${{ runner.temp }}/ghch-changelog.json"
        input_format: "json"
        tee: true
        extensions: |
          i18n
          do
          loopcontrols
          with_
          autoescape
          debug


branding:
  icon: 'sliders'
  color: 'yellow'
