on:
  workflow_call:
    inputs:
      runs-on:
        description: 'runner labels json string'
        default: '[ "ubuntu-latest" ]'
        required: false
        type: string
      template:
        description: 'Template text'
        required: false
        type: string
      template_file:
        description: 'Template file path'
        required: false
        type: string
      owner:
        description: 'git repository owner'
        default: "${{ github.repository_owner }}"
        required: false
        type: string
      repo:
        description: 'git repository name'
        default: "${{ github.event.repository.name }}"
        required: false
        type: string
      git_url:
        description: 'git repository url (owner/repo inputs are ignored)'
        required: false
        type: string
      from:
        description: 'git commit revision range start from'
        required: true
        type: string
      to:
        description: 'git commit revision range end to'
        required: true
        type: string
      host:
        description: 'github host'
        default: github.com
        type: string

    secrets:
      GH_TOKEN:
        required: false
      GH_ENTERPRISE_TOKEN:
        required: false

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_ENTERPRISE_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}

jobs:
  parent-changelog:
    runs-on: "${{ fromJSON(inputs.runs-on) }}"
    outputs:
      submodules: ${{ steps.submodules.outputs.submodules }}
    steps:
      - name: $github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${GITHUB_CONTEXT}"
        if: false
      - uses: actions/checkout@v4
      - name: Get parent changelog
        uses: srz-zumix/changelog-template-action@main
        id: changelog
        with:
          template_file: "${{ inputs.template_file }}"
          owner: "${{ inputs.owner }}"
          repo: "${{ inputs.repo }}"
          git_url: "${{ inputs.git_url }}"
          from: "${{ inputs.from }}"
          to: "${{ inputs.to }}"
      - name: Save to file
        shell: bash
        run: |
          cat << EOS > ${{ steps.changelog.outputs.owner }}-${{ steps.changelog.outputs.repo }}-changelog.md
          ${{ steps.changelog.outputs.text }}
          EOS
      - name: Upload changelog
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.changelog.outputs.owner }}-${{ steps.changelog.outputs.repo }}-changelog.md
          if-no-files-found: error
      - name: Get submodules form/to
        shell: bash
        id: submodules
        env:
          INPUTS_HOST: "${{ inputs.host }}"
          INPUTS_FROM: "${{ inputs.from }}"
          INPUTS_TO: "${{ inputs.to }}"
          INPUTS_OWNER: "${{ steps.changelog.outputs.owner }}"
          INPUTS_REPO: "${{ steps.changelog.outputs.repo }}"
        run: |
          # shellcheck disable=SC2016
          gh api graphql \
            --hostname "${INPUTS_HOST}" \
            -F owner="${INPUTS_OWNER}" \
            -F repo="${INPUTS_REPO}" \
            -F from="${INPUTS_FROM}" \
            -F to="${INPUTS_TO}" \
            -F query='
              query($owner: String!, $repo: String!, $from: String!, $to: String!) {
                repository(owner: $owner, name: $repo) {
                  to: object(expression: $to) {
                    ... Submodules
                  }
                  from: object(expression: $from) {
                    ... Submodules
                  }
              }
            }
            fragment Submodules on Commit {
              submodules(first: 100) {
                nodes {
                  name
                  gitUrl
                  subprojectCommitOid
                }
              }
            }
          ' --jq '
          (.data.repository.to.submodules.nodes[] | [{ key: .name, value: { name: .name, gitUrl: .gitUrl, to : .subprojectCommitOid } }] | from_entries),
          (.data.repository.from.submodules.nodes[] | [{ key: .name, value: { name: .name, gitUrl: .gitUrl, from : .subprojectCommitOid } }] | from_entries)
          ' \
          | jq -s 'reduce .[] as $n ({}; . * $n) | to_entries | [.[].value] | map(select(.from != null and .to != null and .from != .to))' > submodules.json
          SUBMODULES=$(jq -c < submodules.json)
          echo "submodules=${SUBMODULES}" >> "${GITHUB_OUTPUT}"


  submodules-changelog:
    runs-on: "${{ fromJSON(inputs.runs-on) }}"
    needs: parent-changelog
    if: fromJson(needs.parent-changelog.outputs.submodules)[0] != null
    strategy:
      fail-fast: false
      matrix:
        include:
          "${{ fromJson( needs.parent-changelog.outputs.submodules ) }}"
    name: submodules-changelog - ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
        if: inputs.template_file != ''
      - name: Get changelog
        id: changelog
        uses: srz-zumix/changelog-template-action@feature/pr_submodule_diff_comment
        with:
          template: "${{ inputs.template }}"
          template_file: "${{ inputs.template_file }}"
          git_url: "${{ matrix.gitUrl }}"
          from: "${{ matrix.from }}"
          to: "${{ matrix.to }}"
      - name: Save to file
        shell: bash
        run: |
          cat << EOS > ${{ steps.changelog.outputs.owner }}-${{ steps.changelog.outputs.repo }}-changelog.md
          ${{ steps.changelog.outputs.text }}
          EOS
      - name: Upload changelog
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.changelog.outputs.owner }}-${{ steps.changelog.outputs.repo }}-changelog.md
          if-no-files-found: error
