name: TestSelf
on:
  pull_request:
  workflow_dispatch:
    inputs:
      from:
        description: 'git commit revision range start from'
        required: false
      to:
        description: 'git commit revision range end to'
        default: "{{ github.sha || '' }}"
        required: false

permissions:
  contents: read
  pull-requests: read

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: $github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${GITHUB_CONTEXT}"

  test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - name: changelog
        id: changelog
        uses: ./
        with:
          template_file: templates/release-note-with-body.md.j2
          output_file: test.txt
          from: "${{ inputs.from || 'v0.2.0' }}"
          to: "${{ inputs.to || 'v0.3.0' }}"
          tee: true
          debug: true
      - run: |
          cat << EOS | tee output.txt
          ${{ steps.changelog.outputs.text }}
          EOS
          diff output.txt test.txt

  resolve-from-to-test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - name: changelog
        id: changelog
        uses: ./
        with:
          template_file: templates/release-note-with-body.md.j2
          output_file: test.txt
          tee: true
          debug: true
      - run: |
          cat << EOS | tee output.txt
          ${{ steps.changelog.outputs.text }}
          EOS
          diff output.txt test.txt

  resolve-to-test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - name: changelog
        id: changelog
        uses: ./
        with:
          template_file: templates/release-note-with-body.md.j2
          output_file: test.txt
          to: "${{ inputs.to || 'v0.3.0' }}"
          tee: true
          debug: true
      - run: |
          cat << EOS | tee output.txt
          ${{ steps.changelog.outputs.text }}
          EOS
          diff output.txt test.txt
