name: Test
on:
  pull_request:
  workflow_dispatch:
    inputs:
      from:
        description: 'git commit revision range start from'
        required: false
      to:
        description: 'git commit revision range end to'
        default: "{{ github.sha || '' }}"
        required: false
      owner:
        description: 'git repository owner'
        default: 'srz-zumix'
        required: false
      repo:
        description: 'git repository name'
        default: 'changelog-template-action'
        required: false

permissions:
  contents: read
  pull-requests: read

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: $github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${GITHUB_CONTEXT}"

  test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - name: changelog
        id: changelog
        uses: ./
        with:
          template_file: templates/release-note-with-body.md.j2
          output_file: test.txt
          owner: "${{ inputs.owner || 'srz-zumix' }}"
          repo: "${{ inputs.repo || 'gh-activity-report' }}"
          from: "${{ inputs.from || 'v0.4.0' }}"
          to: "${{ inputs.to || 'v0.5.0' }}"
          tee: true
          debug: true
      - run: |
          cat << EOS | tee output.txt
          ${{ steps.changelog.outputs.text }}
          EOS
          diff output.txt test.txt

  resolve-test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - name: changelog
        id: changelog
        uses: ./
        with:
          template_file: templates/release-note-with-body.md.j2
          output_file: test.txt
          owner: "${{ inputs.owner || 'srz-zumix' }}"
          repo: "${{ inputs.repo || 'gh-activity-report' }}"
          tee: true
          debug: true
      - run: |
          cat << EOS | tee output.txt
          ${{ steps.changelog.outputs.text }}
          EOS
          diff output.txt test.txt

  long-diff-test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - name: changelog
        id: changelog
        uses: ./
        with:
          template_file: templates/release-note-with-body.md.j2
          output_file: test.txt
          owner: srz-zumix
          repo: wandbox-api
          from: v0.9.6
          to: v0.10.0
          tee: true
          debug: true
      - run: |
          cat << 'EOS' | tee output.txt
          ${{ steps.changelog.outputs.text }}
          EOS
          diff output.txt test.txt

  behind-diff-test:
    runs-on: macos-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - name: changelog
        id: changelog
        uses: ./
        with:
          template_file: templates/release-note-with-body.md.j2
          output_file: test.txt
          owner: srz-zumix
          repo: wandbox-api
          to: v0.9.6
          from: v0.10.0
          tee: true
          debug: true
      - run: |
          cat << 'EOS' | tee output.txt
          ${{ steps.changelog.outputs.text }}
          EOS
          diff output.txt test.txt
