name: TestReusable PR Submodules Changelog Comment
on:
  pull_request:
  workflow_dispatch:
    inputs:
      from:
        description: 'git commit revision range start from'
        default: "757727599398a020651f59254e7496283d372173"
        required: false
      to:
        description: 'git commit revision range end to'
        default: "b5782867c3424f7ac4fc0469833536000e2e88fa"
        required: false
      owner:
        description: 'git repository owner'
        default: 'srz-zumix'
        required: false
      repo:
        description: 'git repository name'
        default: 'docker-googletest'
        required: false
      pr:
        description: 'pull request number'
        default: '25'
        required: false

permissions:
  contents: read
  pull-requests: read

jobs:
  test-reusable-pr-submodules-changelog-comment:
    uses: ./.github/workflows/reusable-pr-submodules-changelog-comment.yml
    with:
      template: |
        [Compare {{ from_revision }} with {{ to_revision }}]({{ env('GITHUB_SERVER_URL') }}/{{ owner }}/{{ repo }}/compare/{{ from_revision }}...{{ to_revision }})

        ## Changes

        {% for pull_request in pull_requests %}
        {%- if 'login' in pull_request.author %}
        * [{{ pull_request.title }}]({{ pull_request.url }}) - @{{ pull_request.author.login }} {{ pull_request.mergedAt }}
        {%- else %}
        * [{{ pull_request.title }}]({{ pull_request.url }}) - {{ pull_request.mergedAt }}
        {%- endif %}
        {%- endfor %}
      owner: "${{ inputs.owner || 'srz-zumix' }}"
      repo: "${{ inputs.repo || 'docker-googletest' }}"
      from: "${{ inputs.from || '' }}"
      to: "${{ inputs.to || '' }}"
      pr: "${{ inputs.pr || '25' }}"
      gh_comment_options: "--edit-last"
    secrets:
      GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
